---
spring:
  application:
    name: hibernate-search-hang-issue-proof
  datasource:
    url: jdbc:postgresql://localhost:5432/hosc
    username: hosc
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
#          enabled: false
          default_backend: elasticsearch
          backends:
            elasticsearch:
              hosts: localhost:9200
    hibernate:
      ddl-auto: create-drop
  elasticsearch:
    rest:
      uris: http://${spring.jpa.properties.hibernate.search.backends.elasticsearch.hosts}
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: default # WORKAROUND #1

logging:
  level:
    root: info
    org.hibernate: trace

server:
  port: 65529

